name: Weekly cron

on:
  schedule:
    # Weekly Monday 6AM build
    - cron: "0 0 * * 1"

jobs:
  tox:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Python 3.11
            runs-on: ubuntu-latest
            python-version: 3.11
            toxenv: py311

          - name: Python 3.12
            runs-on: ubuntu-latest
            python-version: 3.12
            toxenv: py312

          - name: Python 3.13
            runs-on: ubuntu-latest
            python-version: 3.13
            toxenv: py313

          - name: Code style checks
            runs-on: ubuntu-latest
            python-version: 3.11
            toxenv: style

          - name: Python 3.11 with dev dependencies
            runs-on: ubuntu-latest
            python-version: 3.11
            toxenv: dev
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tox
        run: tox -e ${{ matrix.toxenv }}

  # Kept in a separate job because it needs extra system dependencies
  # that can't be installed by tox.
  build-docs:
    name: Build documentation and check warnings
    runs-on: ubuntu-latest
    steps:
      - name: Install system packages
        run: |
          sudo apt-get install graphviz texlive-latex-extra dvipng
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0
      - name: Set up Python 3.11
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
        with:
          python-version: 3.11
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tox
        run: tox -e build-docs
